- name: 0. Undocumented Prereqs and Unrelated Settings
  hosts: ohpc
  become: true
  tasks:
    # Jetstream2-specific tweaks
    - name: Ensure wheel users get password-less sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/91-wheel-nopasswd
        create: true
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    - name: Check if /etc/ssh/sshd_config.d/50-cloud-init.conf exists
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      register: cloudinit
    - name: Ensure ssh password authentication is enabled
      ansible.builtin.shell: |
        mv /etc/ssh/sshd_config.d/50-cloud-init.conf{,.orig}
      when: cloudinit.stat.exists
    - name: Reload sshd service
      ansible.builtin.service:
        name: sshd
        state: reloaded
    - name: Check if /etc/profile.d/z99-lmod-default-modules.sh exists
      ansible.builtin.stat:
        path: /etc/profile.d/z99-lmod-default-modules.sh
      register: lmod_default_modules
    - name: Ensure lmod doesn't try to load xalt
      ansible.builtin.shell: |
        mv /etc/profile.d/z99-lmod-default-modules.sh{,.orig}
      when: lmod_default_modules.stat.exists

    # Undocumented dependencies for OpenHPC
    - name: Install undocumented package dependencies for default OpenHPC environment
      ansible.builtin.yum:
        name: s-nail

    # Workshop-specific settings
    - name: Add demo users/admins to SMS
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        groups: wheel
        append: true
      loop: "{{ user_creds }}"
    - name: Create a new primary partition on second disk for /opt/ohpc
      community.general.parted:
        device: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:1
        number: 1
        flags: [ lvm ]
        state: present
    - name: Create a volume group on second disk
      community.general.lvg:
        vg: vg.ohpc
        pvs: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:1-part1
        pvresize: true
    - name: Create a logical volume taking all the space in the vg
      community.general.lvol:
        vg: vg.ohpc
        lv: lv.ohpc
        shrink: false
        size: 100%FREE
    - name: Create a filesystem on the vg
      community.general.filesystem:
        fstype: xfs
        dev: /dev/vg.ohpc/lv.ohpc
    - name: Mount /opt/ohpc on the logical volume
      ansible.posix.mount:
        path: /opt/ohpc
        src: /dev/vg.ohpc/lv.ohpc
        fstype: xfs
        state: mounted