- name: 0. Undocumented Prereqs and Unrelated Settings
  hosts: ohpc
  become: true
  tasks:
    - name: Install undocumented package dependencies
      ansible.builtin.yum:
        name: s-nail
    - name: Add demo users/admins to SMS
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        groups: wheel
        append: true
      loop: "{{ user_creds }}"
    - name: Ensure wheel users get password-less sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/91-wheel-nopasswd
        create: true
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    - name: Check if /etc/ssh/sshd_config.d/50-cloud-init.conf exists
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      register: cloudinit
    - name: Ensure ssh password authentication is enabled
      ansible.builtin.shell: |
        mv /etc/ssh/sshd_config.d/50-cloud-init.conf{,.orig}
      when: cloudinit.stat.exists
    - name: Reload sshd service
      ansible.builtin.service:
        name: sshd
        state: reloaded
    - name: Create a new primary partition for LVM
      community.general.parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
    - name: Create a volume group on top of /dev/sdb1
      community.general.lvg:
        vg: vg.ohpc
        pvs: /dev/sdb1
        pvresize: true
    - name: Create a logical volume taking all the space in the vg
      community.general.lvol:
        vg: vg.ohpc
        lv: lv.ohpc
        shrink: false
        size: 100%FREE
    - name: Create a filesystem on the vg
      community.general.filesystem:
        fstype: xfs
        dev: /dev/vg.ohpc/lv.ohpc
    - name: Mount /opt/ohpc
      ansible.posix.mount:
        path: /opt/ohpc
        src: /dev/vg.ohpc/lv.ohpc
        fstype: xfs
        state: mounted