- name: 2. Install Base Operating System
  hosts: ohpc
  become: true
  tasks:
    - name: Add hostname to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "172.16.0.1 {{ ansible_hostname }}"
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
    - name: Set timezone to America/New_York
      community.general.timezone:
        name: America/New_York
