- name: 2. Install Base Operating System
  hosts: sms
  become: true
  tasks:
    - name: Add hostname to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }} sms.localdomain sms"
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

- name: 3. Install OpenHPC Components
  hosts: sms
  become: true
  tasks:
    - name: 3.1 Install OHPC release
      ansible.builtin.yum:
        name: http://repos.openhpc.community/OpenHPC/3/EL_9/{{ arch }}/ohpc-release-3-1.el9.{{ arch }}.rpm
        disable_gpg_check: true
    - name: Check if crb repository is enabled
      ansible.builtin.shell: |
        dnf repolist crb | grep -q enabled
      register: crb_enabled
      changed_when: false
      ignore_errors: true
    - name: Ensure the crb repository is enabled
      ansible.builtin.shell: |
        dnf install -y dnf-plugins-core
        dnf config-manager --set-enabled crb
      when: crb_enabled is failed
    - name: 3.2 Install OHPC docs for install script
      ansible.builtin.package:
        name:
          - docs-ohpc
        state: latest

- name: A. Installation Template
  hosts: sms
  become: true
  tasks:
    - name: Make copy of input.local
      ansible.builtin.copy:
        src: /opt/ohpc/pub/doc/recipes/rocky9/input.local
        dest: /root/input.local
        remote_src: yes
        force: false
    - name: Set provision_wait value in input.local
      ansible.builtin.lineinfile:
        path: /root/input.local
        line: "provision_wait=1"
        search_string: "provision_wait="

    - name: Make copy of recipe.sh
      ansible.builtin.copy:
        src: /opt/ohpc/pub/doc/recipes/rocky9/x86_64/warewulf/slurm/recipe.sh
        dest: /root/recipe.sh
        mode: '0755'
        remote_src: yes
        force: false
    - name: Remove exports commands in recipe.sh
      ansible.builtin.lineinfile:
        path: /root/recipe.sh
        state: absent
        regexp: "/etc/exports"
    - name: Add lines to /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ item.path }} {{ ansible_eth1.ipv4.network }}/{{ ansible_eth1.ipv4.prefix }}(rw,no_subtree_check,fsid={{ item.fsid }}{{ item.options }})"
      loop:
        - { path: '/home', fsid: '10' , options: ',no_root_squash' }
        - { path: '/opt/ohpc/pub', fsid: '11' , options: '' }
    - name: Remove chrony.conf commands in recipe.sh
      ansible.builtin.lineinfile:
        path: /root/recipe.sh
        state: absent
        regexp: " /etc/chrony.conf"
    - name: Add lines to /etc/chrony.conf
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        line: "{{ item }}"
      loop:
        - "local stratum 10"
        - "server 0.centos.pool.ntp.org"
        - "allow {{ ansible_eth1.ipv4.network }}/{{ ansible_eth1.ipv4.prefix }}"

    # - name: Run recipe.sh script
    #   ansible.builtin.shell: |
    #     OHPC_INPUT_LOCAL=/root/input.local /root/recipe.sh
    #   args:
    #     creates: /etc/slurm/slurm.conf
