- name: Z. Post-recipe.sh
  hosts: ohpc
  become: true
  tasks:
    - name: Check for duplicate ReturnToService lines in /etc/slurm/slurm.conf
      ansible.builtin.shell: |
        grep -c '^ReturnToService' /etc/slurm/slurm.conf
      register: returntoservice_lines
      changed_when: false
      ignore_errors: true
    - name: Remove duplicate ReturnToService line from /etc/slurm/slurm.conf
      ansible.builtin.shell: |
        sed -i '0,/ReturnToService=/{/ReturnToService=/d;}' /etc/slurm/slurm.conf
      when: returntoservice_lines.stdout.find('1') == -1
      # https://stackoverflow.com/a/23697254
    - name: Create /var/log/slurmctld.log
      ansible.builtin.file:
        path: /var/log/slurmctld.log
        state: touch
        owner: slurm
        group: slurm
        mode: '0640'
    - name: Restart slurmctld
      ansible.builtin.shell: systemctl restart slurmctld
